# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/addCommunity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_community(object):
    def setupUi(self, Add_community):
        Add_community.setObjectName("Add_community")
        Add_community.resize(640, 140)
        Add_community.move(500,200)
        Add_community.setMinimumSize(QtCore.QSize(500, 140))
        Add_community.setMaximumSize(QtCore.QSize(16777215, 140))
        self.centralwidget = QtWidgets.QWidget(Add_community)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comm_name = QtWidgets.QLineEdit(self.centralwidget)
        self.comm_name.setMinimumSize(QtCore.QSize(200, 30))
        self.comm_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comm_name.setObjectName("comm_name")
        self.gridLayout.addWidget(self.comm_name, 0, 1, 1, 1)
        self.comm_token = QtWidgets.QLineEdit(self.centralwidget)
        self.comm_token.setMinimumSize(QtCore.QSize(200, 30))
        self.comm_token.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comm_token.setObjectName("comm_token")
        self.gridLayout.addWidget(self.comm_token, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_add.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_5.addWidget(self.btn_add)
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setObjectName("btn_close")
        self.btn_close.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        Add_community.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_community)
        QtCore.QMetaObject.connectSlotsByName(Add_community)

    def retranslateUi(self, Add_community):
        _translate = QtCore.QCoreApplication.translate
        Add_community.setWindowTitle(_translate("Add_community", "Add community"))
        self.label_2.setText(_translate("Add_community", "Токен"))
        self.label_5.setText(_translate("Add_community", "Сообщество"))
        self.btn_add.setText(_translate("Add_community", "Добавить"))
        self.btn_close.setText(_translate("Add_community", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_community = QtWidgets.QMainWindow()
    ui = Ui_Add_community()
    ui.setupUi(Add_community)
    Add_community.show()
    sys.exit(app.exec_())
