# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 480)
        MainWindow.move(500, 100)
        MainWindow.setMinimumSize(QtCore.QSize(650, 480))
        MainWindow.setMaximumSize(QtCore.QSize(650, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(100, 30))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.combo_comm = QtWidgets.QComboBox(self.centralwidget)
        self.combo_comm.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_comm.setMaximumSize(QtCore.QSize(16777215, 30))
        self.combo_comm.setPlaceholderText("")
        self.combo_comm.setObjectName("combo_comm")
        self.horizontalLayout_4.addWidget(self.combo_comm)
        self.btn_edit_comm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_comm.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_edit_comm.setObjectName("btn_edit_comm")
        self.horizontalLayout_4.addWidget(self.btn_edit_comm)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.text_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_log.setObjectName("text_log")
        self.text_log.setReadOnly(1)
        self.gridLayout.addWidget(self.text_log, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 30))
        self.label.setMaximumSize(QtCore.QSize(100, 30))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textEdit_addr = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_addr.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_addr.setObjectName("textEdit_addr")
        self.horizontalLayout_2.addWidget(self.textEdit_addr)
        self.btn_addr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addr.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_addr.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_addr.setObjectName("btn_addr")
        self.horizontalLayout_2.addWidget(self.btn_addr)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 30))
        self.label_3.setMaximumSize(QtCore.QSize(100, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.textEdit_mess = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_mess.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_mess.setObjectName("textEdit_mess")
        self.horizontalLayout_3.addWidget(self.textEdit_mess)
        self.btn_mess = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mess.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_mess.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_mess.setObjectName("btn_mess")
        self.horizontalLayout_3.addWidget(self.btn_mess)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рассылка сообщений ВК"))
        self.label_4.setText(_translate("MainWindow", "Сообщество"))
        self.btn_edit_comm.setText(_translate("MainWindow", "добавить"))
        self.btn_start.setText(_translate("MainWindow", "начать рассылку"))
        self.btn_close.setText(_translate("MainWindow", "закрыть"))
        self.label.setText(_translate("MainWindow", "Адресаты"))
        self.btn_addr.setText(_translate("MainWindow", "выбрать"))
        self.label_3.setText(_translate("MainWindow", "Сообщение"))
        self.btn_mess.setText(_translate("MainWindow", "выбрать"))

    def add_function(self):
        self.btn_addr.clicked.connect(lambda: self.select_file('addr'))
        self.btn_mess.clicked.connect(lambda: self.select_file('mess'))


    def select_file(self, btn):
        file = QtWidgets.QFileDialog.getOpenFileName()[0]
        if btn == 'addr':
            self.textEdit_addr.setText(file)
        if btn == 'mess':
            self.textEdit_mess.setText(file)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
